# -*- coding: utf-8 -*-
"""analisededados_ferroviarios.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nm_8zK4HXKfTnOsjLPp19qjjKZQFdpbq
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.cluster import AgglomerativeClustering
import io

# Configuração da Página
st.set_page_config(page_title="Análise Ferroviária", layout="wide")
st.title("📊 Projeto de Análise de Dados Ferroroviários")


# Criando dados fictícios baseados nos indicadores dos fontes
data = {
    'trem_id': ['TR-100', 'TR-101', 'TR-102', 'TR-103', 'TR-104', 'TR-105', 'TR-100', 'TR-106', 'TR-107', 'TR-108'],
    'linha': ['LN-01', 'LN-02', 'LN-03', 'LN-03', 'LN-01', 'LN-02', 'LN-01', 'LN-03', 'LN-02', 'LN-01'],
    'atraso_min': [10, 45, 132, 80, 15, np.nan, 10, 95, 20, 5], # Inclui o máximo de 132 min e um valor nulo [2]
    'passageiros': [250, 230, 245, 260, 220, 240, 255, 235, 265, 215], # Média próxima a 242 [2]
    'carga_ton': [1250, 1300, 1280, 1350, 1200, 1290, 1270, 1310, 1330, 1260], # Média próxima a 1280 [2]
    'clima': ['sol', 'chuva', 'tempestade', 'nublado', 'sol', 'CHUVA', 'sol', 'tempestade', 'nublado', 'sol'], # Teste de padronização [1]
    'velocidade_media_kmh': [80, 75, 60, 70, 85, 78, 82, 65, 72, 88],
    'status_viagem': ['Concluída', 'Atrasada', 'Atrasada', 'Atrasada', 'Concluída', 'Concluída', 'Concluída', 'Atrasada', 'Concluída', 'Concluída'],
    'consumo_energia_kwh': [1500, 1600, 1800, 1700, 1400, 1550, 1520, 1750, 1650, 1450],
    'distancia_km': [100, 120, 90, 110, 130, 105, 95, 115, 125, 135]
}

df_ficticio = pd.DataFrame(data)

# Salvando o arquivo
df_ficticio.to_csv("viagens.csv", index=False)
print("Arquivo 'viagens.csv' criado com sucesso!")


# --- CARREGAMENTO E LIMPEZA DE DADOS ---
@st.cache_data
def load_data():
    # Simulando o carregamento conforme a metodologia dos fontes [1-3]
    df = df_ficticio

    # 1. Limpeza [1]
    df = df.drop_duplicates()
    df["atraso_min"] = df["atraso_min"].fillna(df["atraso_min"].mean())

    # 2. Proteção/Anonimização [1]
    df["trem_id_cod"] = df["trem_id"].astype("category").cat.codes

    # 3. Padronização [1]
    df["clima"] = df["clima"].str.upper()

    return df

df = load_data()

# --- SIDEBAR: Navegação ---
menu = st.sidebar.selectbox("Navegação", ["Resumo Operacional", "Clusterização", "Manutenção"])

if menu == "Resumo Operacional":
    st.header("📌 Estatística Descritiva")

    # Métricas principais baseadas nos resultados [4]
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Média de Atraso", "38 min")
    col2.metric("Maior Atraso", "132 min")
    col3.metric("Média de Passageiros", "242")
    col4.metric("Média de Carga", "1280 ton")

    # Gráficos Categóricos [5]
    col_a, col_b = st.columns(2)

    with col_a:
        st.subheader("Status das Viagens")
        fig1, ax1 = plt.subplots()
        df["status_viagem"].value_counts().plot(kind='pie', autopct='%1.1f%%', ax=ax1)
        st.pyplot(fig1)

    with col_b:
        st.subheader("Atraso Médio por Linha")
        fig2, ax2 = plt.subplots()
        media_linha = df.groupby("linha")["atraso_min"].mean()
        media_linha.plot(kind='bar', color='orange', ax=ax2)
        plt.ylabel("Minutos")
        st.pyplot(fig2)
        st.info("A linha LN-03 apresenta o maior índice de atraso [6, 7].")

elif menu == "Clusterização":
    st.header("🧠 Padrões Operacionais (Clustering)")

    # Executando o modelo AgglomerativeClustering dos fontes [8]
    X = df[["atraso_min", "velocidade_media_kmh", "carga_ton"]]
    modelo = AgglomerativeClustering(n_clusters=3, linkage='ward')
    df["cluster"] = modelo.fit_predict(X)

    st.write("Foram identificados 3 grupos principais [8, 9]:")
    st.markdown("- **Cluster 0:** Viagens Eficientes")
    st.markdown("- **Cluster 1:** Alto Atraso (frequentemente em clima severo)")
    st.markdown("- **Cluster 2:** Alta Carga e Alto Consumo")

    # Visualização da Dispersão
    fig3, ax3 = plt.subplots()
    sns.scatterplot(data=df, x="velocidade_media_kmh", y="carga_ton", hue="cluster", palette="viridis")
    st.pyplot(fig3)

elif menu == "Manutenção":
    st.header("🔧 Análise de Falhas e Manutenção")

    # Dados de manutenção baseados nos fontes [2, 3]
    manutencao_data = """id_manutencao,trem_id,tipo,custo_brl,tempo_parado_h,falha_detectada
    5001,TR-100,Preventiva,12000,6,NÃO
    5002,TR-101,Corretiva,45000,18,SIM
    5003,TR-102,Preventiva,15000,8,NÃO
    5004,TR-103,Corretiva,67000,24,SIM"""
    df_man = pd.read_csv(io.StringIO(manutencao_data))

    # Trens com mais falhas [9, 10]
    st.subheader("Trens Críticos")
    trens_falhas = df_man[df_man['falha_detectada'] == 'SIM']
    st.table(trens_falhas[['trem_id', 'tipo', 'custo_brl', 'tempo_parado_h']])
    st.warning("Os trens TR-101 e TR-103 requerem atenção imediata devido a falhas detectadas [3, 9].")